"""`examples`: write one documentation page per task item.

Three hundred and sixty pages is not something to maintain by hand, so this
generates all of them from the task set and the recorded attempts. Each page is
a thin MDX shell around its own JSON file: the page carries only its item, so
opening one example does not download every example.

Run it after `publish`; both read the same attempts.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Annotated

import typer

from llmsearchbench.paths import RESULTS, SITE, SITE_DOCS, TASKS
from llmsearchbench.providers import UnknownModelError, get_model
from llmsearchbench.scoring.tooluse import outcome_for
from llmsearchbench.storage import load_attempts, read_jsonl
from llmsearchbench.types.discrimination import DiscriminationTask
from llmsearchbench.types.enums import ToolProtocol
from llmsearchbench.types.examples import ExampleModelResult, ExampleReport
from llmsearchbench.types.tooluse import ToolUseAttempt, ToolUseTask
from llmsearchbench.ui import console, warn

app = typer.Typer()

TASK_SET = "tool-use-correctness"
DISCRIMINATION_SET = "search-result-discrimination"

#: How much of an answer a page shows. Long enough to judge whether the model
#: actually knew the thing; short enough that 34 of them stay readable.
EXCERPT = 320


def unslug(name: str) -> str:
    return name.replace("--", "/", 1).replace("-attempts", "")


def page_source(item_id: str) -> str:
    """The MDX for one item.

    Deliberately almost empty: everything a reader sees comes from the JSON
    next to it, so a change to the layout is one component edit rather than
    360 file rewrites.
    """
    return (
        "---\n"
        f"id: {item_id}\n"
        f"title: {item_id}\n"
        f"sidebar_label: {item_id}\n"
        "hide_table_of_contents: true\n"
        f"description: What every model did with task item {item_id}.\n"
        "---\n"
        "\n"
        "{/* Generated by `llmsearchbench examples`. Do not edit by hand. */}\n"
        "\n"
        "import ExampleReport from '@site/src/components/ExampleReport';\n"
        f"import report from '@site/src/data/examples/{item_id}.json';\n"
        "\n"
        "<ExampleReport report={report} />\n"
    )


def result_for(task: ToolUseTask, attempt: ToolUseAttempt, model_id: str) -> ExampleModelResult:
    outcome = outcome_for(task, attempt)
    call = next(iter(attempt.calls), None)
    try:
        label = get_model(model_id).label
    except UnknownModelError:
        label = model_id

    return ExampleModelResult(
        model=model_id,
        label=label,
        tool_protocol=attempt.tool_protocol,
        searched=outcome.searched,
        correct=outcome.decision_correct,
        query=call.query if call else "",
        call_problem=", ".join(str(problem) for problem in outcome.problems),
        answer_excerpt=attempt.answer[:EXCERPT].strip(),
    )


@app.command("examples")
def examples(
    results_dir: Annotated[Path, typer.Option(help="Where attempts live.")] = (
        RESULTS / "local"
    ),
    task_set: Annotated[Path, typer.Option(help="The task set.")] = TASKS / f"{TASK_SET}.jsonl",
    site: Annotated[Path, typer.Option(help="The documentation site root.")] = SITE,
) -> None:
    """Write one page per task item, with what every model did on it."""
    tasks = [ToolUseTask.model_validate(raw) for raw in read_jsonl(task_set)]

    # Only complete runs: a model that answered half the set would appear on
    # some pages and not others, which reads as a difference between items.
    runs: dict[str, dict[str, ToolUseAttempt]] = {}
    for path in sorted(results_dir.glob("*-attempts.jsonl")):
        model_id = unslug(path.stem)
        by_id = {a.task_id: a for a in load_attempts(path) if not a.failed}
        if len(by_id) == len(tasks):
            runs[model_id] = by_id

    if not runs:
        warn("no complete runs; nothing to write")
        return

    data_dir = site / "src" / "data" / "examples"
    page_dir = SITE_DOCS / "examples" if site == SITE else site / "content" / "examples"
    for directory in (data_dir, page_dir):
        # Rebuilt wholesale: a renamed or dropped item should not leave a page
        # behind saying otherwise.
        shutil.rmtree(directory, ignore_errors=True)
        directory.mkdir(parents=True, exist_ok=True)

    for task in tasks:
        report = ExampleReport(
            id=task.id,
            bucket=str(task.bucket),
            subcategory=task.subcategory,
            source=task.source,
            source_id=task.source_id or "",
            adversarial=task.adversarial,
            prompt=task.prompt,
            gold_answer=task.gold_answer,
            rationale=task.rationale,
            expects_search=task.expects_search,
            results=[
                result_for(task, by_id[task.id], model_id)
                for model_id, by_id in sorted(runs.items())
            ],
        )
        (data_dir / f"{task.id}.json").write_text(
            report.model_dump_json(indent=2, exclude_none=True) + "\n", encoding="utf-8"
        )
        (page_dir / f"{task.id}.mdx").write_text(page_source(task.id), encoding="utf-8")

    prompted = [
        model_id
        for model_id, by_id in runs.items()
        if by_id[tasks[0].id].tool_protocol is ToolProtocol.PROMPTED
    ]
    console.print(
        f"[ok]wrote[/ok] {len(tasks)} example page(s) from {len(runs)} complete run(s)"
    )
    if prompted:
        console.print(
            f"[muted]{len(prompted)} run(s) used the prompted protocol; "
            "the pages say so.[/muted]"
        )


def discrimination_page_source(item_id: str) -> str:
    """The MDX for one discrimination item."""
    return (
        "---\n"
        f"id: {item_id}\n"
        f"title: {item_id}\n"
        f"sidebar_label: {item_id}\n"
        "hide_table_of_contents: true\n"
        f"description: The candidate set for task item {item_id}, with its grades.\n"
        "---\n"
        "\n"
        "{/* Generated by `llmsearchbench examples-discrimination`. Do not edit by hand. */}\n"
        "\n"
        "import DiscriminationExample from '@site/src/components/DiscriminationExample';\n"
        f"import item from '@site/src/data/discrimination/{item_id}.json';\n"
        "\n"
        "<DiscriminationExample item={item} />\n"
    )


@app.command("examples-discrimination")
def examples_discrimination(
    task_set: Annotated[Path, typer.Option(help="The shipped task set.")] = (
        TASKS / f"{DISCRIMINATION_SET}.jsonl"
    ),
    local_set: Annotated[Path, typer.Option(help="The locally built half.")] = (
        TASKS / "local" / f"{DISCRIMINATION_SET}-local.jsonl"
    ),
    site: Annotated[Path, typer.Option(help="The documentation site root.")] = SITE,
) -> None:
    """Write one page per discrimination item, so the set can be read by hand.

    Items whose passages come from MS MARCO are written to the same folders as
    the rest and ignored by git: the site you publish carries only what it may
    redistribute, while the site you run locally carries everything.
    """
    if not task_set.exists():
        warn(f"no task set at {task_set} - run `make tasks-discrimination`")
        return

    items = [DiscriminationTask.model_validate(raw) for raw in read_jsonl(task_set)]
    local: list[DiscriminationTask] = []
    if local_set.exists():
        local = [DiscriminationTask.model_validate(raw) for raw in read_jsonl(local_set)]
    items += local

    data_dir = site / "src" / "data" / "discrimination"
    page_dir = site / "content" / "discrimination-examples"
    for directory in (data_dir, page_dir):
        shutil.rmtree(directory, ignore_errors=True)
        directory.mkdir(parents=True, exist_ok=True)

    for item in items:
        (data_dir / f"{item.id}.json").write_text(
            item.model_dump_json(indent=2) + "\n", encoding="utf-8"
        )
        (page_dir / f"{item.id}.mdx").write_text(
            discrimination_page_source(item.id), encoding="utf-8"
        )

    console.print(
        f"[ok]wrote[/ok] {len(items)} example page(s) "
        f"[muted]({len(items) - len(local)} shipped, {len(local)} local-only)[/muted]"
    )
    if not local:
        console.print(
            "[muted]no locally built items; run `make tasks-discrimination` to read "
            "the web and no-answer categories here too.[/muted]"
        )
