"""Regenerate the open-weight coverage table in the documentation.

    uv run python scripts/open_weight_coverage.py

Reads the live OpenRouter catalogue, checks Hugging Face for published
weights, and writes
`docs/content/tasks/tool-use-correctness/open-weight-coverage.md`.

Open-weight status is *verified*, not assumed: for a fine-tuning decision a
guess is worse than nothing, and several of these models postdate any given
model's training data. A model counts as open only when its exact weights repo
resolves on Hugging Face.

Needs the network. Run it by hand when the upstream catalogue changes.
"""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.request
from datetime import date

from llmsearchbench.paths import SITE_DOCS
from llmsearchbench.providers import MODELS
from llmsearchbench.providers.weights import WEIGHTS

OPENROUTER = "https://openrouter.ai/api/v1/models"
HUGGINGFACE = "https://huggingface.co/api/models/"
PAGE = SITE_DOCS / "tasks" / "tool-use-correctness" / "open-weight-coverage.md"

#: Medians measured across the completed Qwen sweep, used to price a run for
#: models that have not been run. Output varied 18K to 343K, so this is a rough
#: figure and a thinking model will exceed it.
RUN_IN, RUN_OUT = 93_372, 87_235

#: Vendors this page covers, and the label to group them under.
VENDORS = {
    "openai": "GPT-OSS",
    "z-ai": "Z.ai (GLM)",
    "deepseek": "DeepSeek",
    "nvidia": "Nemotron",
    "thinkingmachines": "Thinking Machines",
    "moonshotai": "Kimi (Moonshot)",
    "minimax": "MiniMax",
    "xiaomi": "Xiaomi (MiMo)",
    "meta-llama": "Llama",
    "meta": "Meta (Muse)",
    "mistralai": "Mistral",
    "meituan": "Meituan (LongCat)",
    "tencent": "Tencent (Hunyuan)",
    "dots-studio": "DotsStudio",
    "sakana": "Sakana",
}

#: Providers reached directly rather than through OpenRouter, so they do not
#: appear in its catalogue and are described by hand.
DIRECT_PROVIDERS = """## Avey

Reached directly at `staging1.api.avey.ai`, not through OpenRouter.

| Model | Weights | Reasoning | Tools | Run? |
| --- | --- | --- | :---: | :---: |
| `avey/olive` | not published | yes, always on | **N** | blocked |

`avey/olive` **cannot run this benchmark as deployed.** Its vLLM server was
started without `--enable-auto-tool-choice` and `--tool-call-parser`, so any
request carrying `tools` is rejected with a 400. Every variant fails:
`tool_choice` omitted or `auto` errors, a forced function errors, and
`tool_choice: "none"` is accepted but by definition never calls the tool — which
is the thing being measured. The provider has to set those flags; there is no
client-side workaround.

The adapter and catalogue entry are in place, so the model runs the moment they
do. Avey publishes no price, so its cost figures would read zero and must not be
compared with a priced model.
"""


def licence_of(repo: str) -> str | None:
    """The licence on a Hugging Face repo, or None when it does not exist."""
    try:
        with urllib.request.urlopen(HUGGINGFACE + repo, timeout=20) as response:
            model = json.load(response)
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError):
        return None
    return (model.get("cardData") or {}).get("license") or "unstated"


def reasoning(supported: set[str]) -> str:
    if "reasoning_effort" in supported:
        return "effort levels"
    if "reasoning" in supported:
        return "on / off"
    return "none"


def main() -> None:
    with urllib.request.urlopen(OPENROUTER, timeout=30) as response:
        catalogue = json.load(response)["data"]

    ours = set(MODELS)
    # Kimi is catalogued against Moonshot's own API, under a different id.
    ours |= {
        "moonshotai/" + model_id.split("/", 1)[1]
        for model_id in MODELS
        if model_id.startswith("moonshot/")
    }

    licences: dict[str, str | None] = {}
    for model_id, repo in WEIGHTS.items():
        licences[model_id] = licence_of(repo)
        time.sleep(0.05)

    lines = [
        "---",
        "id: open-weight-coverage",
        "title: Open-weight coverage",
        "sidebar_position: 8",
        "description: Which open-weight models this benchmark has run, and which it has not.",
        "---",
        "",
        "<!-- Generated by `uv run python scripts/open_weight_coverage.py`. "
        "Do not edit by hand. -->",
        "",
        "# Open-weight coverage",
        "",
        f"As of {date.today().isoformat()}. Only models whose **weights are actually "
        "published** are candidates here — the point of this page is deciding what "
        "could be fine-tuned, and for that a guess is worse than nothing.",
        "",
        "Open-weight status is verified against Hugging Face at generation time, not "
        "assumed. A model counts as open only when its exact weights repository "
        "resolves.",
        "",
        "**Run cost** prices a full 360-item run from token counts measured on real "
        "runs. Output varied by a factor of nineteen across models, so treat it as an "
        "order of magnitude, not a quote.",
        "",
    ]

    for vendor, label in VENDORS.items():
        models = sorted(
            (m for m in catalogue if m["id"].split("/")[0] == vendor),
            key=lambda m: m["id"],
        )
        if vendor == "openai":
            models = [m for m in models if "oss" in m["id"]]
        if not models:
            lines += [f"## {label}", "", "Nothing from this vendor on OpenRouter.", ""]
            continue

        lines += [
            f"## {label}",
            "",
            "| Model | Weights | Licence | Reasoning | Tools | Run cost | Run? |",
            "| --- | --- | --- | --- | :---: | ---: | :---: |",
        ]
        for model in models:
            supported = set(model.get("supported_parameters") or [])
            pricing = model["pricing"]
            price_in = float(pricing["prompt"]) * 1e6
            price_out = float(pricing["completion"]) * 1e6
            run = RUN_IN / 1e6 * price_in + RUN_OUT / 1e6 * price_out

            model_id = model["id"]
            checked = model_id in licences
            licence = licences.get(model_id)
            if not checked:
                weights, licence_text = "not checked", "—"
            elif licence is None:
                weights, licence_text = "**no**", "—"
            else:
                weights, licence_text = "yes", licence

            has_tools = "tools" in supported
            if model_id in ours:
                mark = "**yes**"
            elif not has_tools:
                mark = "n/a"
            else:
                mark = "—"

            lines.append(
                f"| `{model_id.split('/', 1)[1]}` | {weights} | {licence_text} | "
                f"{reasoning(supported)} | {'y' if has_tools else 'N'} | "
                f"${run:.3f} | {mark} |"
            )
        lines.append("")

    lines += [DIRECT_PROVIDERS, ""]

    lines += [
        "## How a model gets on the run list",
        "",
        "Three gates, in order:",
        "",
        "1. **Weights published.** No repository on Hugging Face, no entry. This rules "
        "out Sakana's Fugu line, Meta's Muse line, Tencent's HY4, DotsStudio's dots-3, "
        "Xiaomi's v2.6 tier, and Mistral's commercial tier — all API-only.",
        "2. **Tool calling supported.** The benchmark *is* a tool call. Several "
        "open-weight models fail here, including Tencent's Hunyuan A13B and the "
        "DeepSeek R1 distills — and one whole provider, Avey, whose server has "
        "tool calling switched off.",
        "3. **Actually served.** `meta-llama/llama-4-scout` is listed by "
        "OpenRouter but every request returns *No endpoints found*: the listing "
        "exists, the capacity does not. It was dropped after 720 failed calls.",
        "4. **Adds something.** One model per family per size tier. Vision and coder "
        "variants are skipped unless they answer a specific question — a coder model "
        "is included as a control, to see whether code tuning changes tool judgement.",
        "",
        "## Licences worth reading before fine-tuning",
        "",
        "A licence of `other` is not a red flag by itself, but it is not Apache or MIT "
        "either. Llama, Nemotron, MiniMax and Kimi all use custom terms with "
        "attribution or use restrictions. The unencumbered bases here are the "
        "Apache-2.0 and MIT rows.",
        "",
        "## Routing",
        "",
        "Kimi runs against **Moonshot's own API**, not OpenRouter, because a key for it "
        "was available. Its price in the results is the OpenRouter listing for the same "
        "weights, used as a proxy — Moonshot does not publish machine-readable pricing. "
        "A model called through different routes is not strictly comparable; the route "
        "is recorded with every run.",
        "",
    ]

    PAGE.parent.mkdir(parents=True, exist_ok=True)
    PAGE.write_text("\n".join(lines), encoding="utf-8")
    ran = sum(1 for m in catalogue if m["id"] in ours)
    print(f"wrote {PAGE}  ({ran} model(s) marked as run)")


if __name__ == "__main__":
    main()
