"""Regenerate the Qwen coverage table in the documentation.

    uv run python scripts/qwen_coverage.py

Reads the live OpenRouter catalogue, marks which models this benchmark has
catalogued, and writes `docs/content/tasks/tool-use-correctness/qwen-coverage.mdx`.

Kept as a script rather than a CLI command because it needs the network and is
run by hand when the upstream catalogue changes, not as part of any gate.
"""

from __future__ import annotations

import json
import re
import urllib.request
from collections import defaultdict
from datetime import date

from llmsearchbench.paths import SITE_DOCS
from llmsearchbench.providers import MODELS

ENDPOINT = "https://openrouter.ai/api/v1/models"
PAGE = SITE_DOCS / "tasks" / "tool-use-correctness" / "qwen-coverage.md"

#: Measured on the first completed run: 110,459 input and 87,325 output tokens
#: over 360 items. Used to price a run for models that have not been run.
RUN_IN, RUN_OUT = 110_459, 87_325


def reasoning(supported: set[str]) -> str:
    if "reasoning_effort" in supported:
        return "effort levels"
    if "reasoning" in supported:
        return "on / off"
    return "none"


def generation(model_id: str) -> str:
    match = re.match(r"qwen-?([0-9.]+)", model_id.split("/")[1])
    return match.group(1) if match else "other"


def main() -> None:
    with urllib.request.urlopen(ENDPOINT, timeout=30) as response:
        catalogue = json.load(response)["data"]

    qwen = [m for m in catalogue if m["id"].startswith("qwen/")]
    ours = set(MODELS)

    by_generation: dict[str, list[dict]] = defaultdict(list)
    for model in qwen:
        by_generation[generation(model["id"])].append(model)

    lines = [
        "---",
        "id: qwen-coverage",
        "title: Qwen coverage",
        "sidebar_position: 7",
        "description: Every Qwen model on OpenRouter, and which ones this benchmark has run.",
        "---",
        "",
        "<!-- Generated by `uv run python scripts/qwen_coverage.py`. Do not edit by hand. -->",
        "",
        "# Qwen coverage",
        "",
        f"Every Qwen model OpenRouter serves, as of {date.today().isoformat()}. "
        "A tick means this benchmark has run it.",
        "",
        "The **run cost** column prices a full 360-item run using the token counts "
        "measured on the first completed run. Thinking models will exceed it, often "
        "by a lot — treat it as a floor.",
        "",
    ]

    total = len(qwen)
    tried = sum(1 for m in qwen if m["id"] in ours)
    no_tools = [m for m in qwen if "tools" not in (m.get("supported_parameters") or [])]

    lines += [
        "| | Count |",
        "| --- | ---: |",
        f"| Qwen models on OpenRouter | {total} |",
        f"| Cannot run — no tool calling | {len(no_tools)} |",
        f"| Run by this benchmark | {tried} |",
        f"| Not yet run | {total - tried - len(no_tools)} |",
        "",
    ]

    for gen in sorted(by_generation, key=lambda g: (g == "other", g)):
        models = sorted(by_generation[gen], key=lambda m: m["id"])
        label = "Other" if gen == "other" else f"Qwen {gen}"
        lines += [
            f"## {label}",
            "",
            "| Model | Reasoning | Context | Out $/M | Run cost | Run? |",
            "| --- | --- | ---: | ---: | ---: | :---: |",
        ]
        for model in models:
            supported = set(model.get("supported_parameters") or [])
            pricing = model["pricing"]
            price_in = float(pricing["prompt"]) * 1e6
            price_out = float(pricing["completion"]) * 1e6
            run = RUN_IN / 1e6 * price_in + RUN_OUT / 1e6 * price_out
            has_tools = "tools" in supported

            if not has_tools:
                mark = "n/a"
                note = "no tool calling"
            elif model["id"] in ours:
                mark = "**yes**"
                note = reasoning(supported)
            else:
                mark = "—"
                note = reasoning(supported)

            context = model.get("context_length") or 0
            lines.append(
                f"| `{model['id'].split('/')[1]}` | {note} | {context:,} | "
                f"{price_out:.3f} | ${run:.3f} | {mark} |"
            )
        lines.append("")

    lines += [
        "## Why the untried ones were left out",
        "",
        "Not an oversight — each group was skipped for a reason:",
        "",
        "**No tool calling.** The benchmark *is* a tool call, so these cannot run at all.",
        "",
        "**Vision variants (`-vl-`).** Same weights plus a vision tower, and every "
        "prompt in this task is text. Running them re-measures the text model at a "
        "higher price.",
        "",
        "**Coder variants.** Tuned for code, while the task is general facts and "
        "conversation. One is included as a control; the rest would score badly for "
        "reasons that say nothing about tool judgement.",
        "",
        "**Dated snapshots.** `qwen-plus-2025-07-28` and `qwen3.5-plus-02-15` are "
        "point-in-time copies of models already covered.",
        "",
        "**The max tier.** Not wrong, just expensive, and its members move together. "
        "Worth adding one if a ceiling is wanted.",
        "",
        "To add any of them: put a `ModelSpec` in "
        "`src/llmsearchbench/providers/registry.py` with the price from the table "
        "above, then rerun this script to update the ticks.",
        "",
    ]

    PAGE.parent.mkdir(parents=True, exist_ok=True)
    PAGE.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {PAGE}  ({tried}/{total} run)")


if __name__ == "__main__":
    main()
